"use client";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./ThemeProvider";
import { Toaster } from "sonner";
import Navbar from "@/components/website/Navbar";
import { cn } from "@/lib/utils";

const josefin = Josefin_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ParadoxUi",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={cn(josefin.className, {
          "debug-screens": process.env.NODE_ENV === "development",
        })}
      >
        <div className=" w-10/12 mx-auto">
          <Navbar />
        </div>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="xl:w-10/12 lg:w-11/12 overflow-hidden mx-auto">{children}</div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
