"use client";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./ThemeProvider";
import { Toaster } from "sonner";
import Navbar from "@/components/website/Navbar";

const josefin = Josefin_Sans({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "ParadoxUi",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={josefin.className}>
        <div className=" w-10/12 mx-auto">
          <Navbar />
        </div>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" w-10/12 mx-auto  overflow-hidden">{children}</div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
